version: "3.5"
services:
  frontend-user:
    image: frontend-user
    container_name: frontend-user
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "3008:3008"
